<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.9.3.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'RRAPT',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Appointments',
  'published_date' => '2018-03-14 14:05:35',
  'type' => 'module',
  'version' => 1521036335,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Appointments',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'RRAPT_Calendar',
      'class' => 'RRAPT_Calendar',
      'path' => 'modules/RRAPT_Calendar/RRAPT_Calendar.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'RRAPT_Admin',
      'class' => 'RRAPT_Admin',
      'path' => 'modules/RRAPT_Admin/RRAPT_Admin.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RRAPT_Calendar',
      'to' => 'modules/RRAPT_Calendar',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RRAPT_Admin',
      'to' => 'modules/RRAPT_Admin',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);