<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.9.3.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'abc',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Custom_Package',
  'published_date' => '2018-03-16 13:40:56',
  'type' => 'module',
  'version' => 1521207656,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Custom_Package',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'abc_Properties',
      'class' => 'abc_Properties',
      'path' => 'modules/abc_Properties/abc_Properties.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'abc_Mortgages',
      'class' => 'abc_Mortgages',
      'path' => 'modules/abc_Mortgages/abc_Mortgages.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'abc_Deedbacks',
      'class' => 'abc_Deedbacks',
      'path' => 'modules/abc_Deedbacks/abc_Deedbacks.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'abc_Estoppels',
      'class' => 'abc_Estoppels',
      'path' => 'modules/abc_Estoppels/abc_Estoppels.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'abc_Inventories',
      'class' => 'abc_Inventories',
      'path' => 'modules/abc_Inventories/abc_Inventories.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'abc_Maintenance_Fees',
      'class' => 'abc_Maintenance_Fees',
      'path' => 'modules/abc_Maintenance_Fees/abc_Maintenance_Fees.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'abc_Transfers',
      'class' => 'abc_Transfers',
      'path' => 'modules/abc_Transfers/abc_Transfers.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/abc_Properties',
      'to' => 'modules/abc_Properties',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/abc_Mortgages',
      'to' => 'modules/abc_Mortgages',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/abc_Deedbacks',
      'to' => 'modules/abc_Deedbacks',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/abc_Estoppels',
      'to' => 'modules/abc_Estoppels',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/abc_Inventories',
      'to' => 'modules/abc_Inventories',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/abc_Maintenance_Fees',
      'to' => 'modules/abc_Maintenance_Fees',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/abc_Transfers',
      'to' => 'modules/abc_Transfers',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);