<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
    'acceptable_sugar_flavors' => array(
        'PRO',
        'CORP',
        'ENT',
        'ULT'
    ),
    'acceptable_sugar_versions' => array(
        'exact_matches' => array(),
        'regex_matches' => array('7\\..*$'),
    ),
    'author' => 'Intelestream Inc.',
    'name' => 'Intelestream Deploy Helper',
    'readme'=>"",
    'description' => 'Intelestream Deploy Helper',
    'published_date' => 'August 29th, 2017',
    'is_uninstallable' => true,
    'type' => 'module',
    'version' => '1.5.0',
    'key'=>'INTCR',
);


$installdefs = array (
  'id' => 'INT_DeployHelper',
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
    'administration' => array(
        array(
           'from' => '<basepath>/custom/Extension/modules/Administration/Ext/Administration/INT_DeployHelperAdmin.php'
        )
    ),
    'extensions' => array(
        array(
            'from' => '<basepath>/custom/Extension/application/Ext/Extension/INT_DeployHelper.php'
        )
    ),
  'copy' => 
  array (
    array (
        'from' => '<basepath>/custom/themes/default/images/int.png',
        'to' => 'custom/themes/default/images/int.png',
    ),
    array (
        'from' => '<basepath>/INT_DeployHelper',
        'to' => 'modules/INT_DeployHelper',
    ),
    array (
         'from' => '<basepath>/custom/Extension/application/Ext/JSGroupings/INT_DeployHelperJS.php',
         'to' => 'custom/Extension/application/Ext/JSGroupings/INT_DeployHelperJS.php',
    ),
    array (
         'from' => '<basepath>/custom/Extension/application/Ext/Include/INT_DeployHelper.php',
         'to' => 'custom/Extension/application/Ext/Include/INT_DeployHelper.php',
    ),
  ),
  'language' => 
  array (
    array (
        'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.INT_DeployHelper.php',
        'to_module' => 'application',
        'language' => 'en_us',
    ),
  ),
);