<?php
// created: 2018-03-27 05:46:25
$dictionary["abc_Estoppels"]["fields"]["abc_estoppels_abc_estoppels_1"] = array (
  'name' => 'abc_estoppels_abc_estoppels_1',
  'type' => 'link',
  'relationship' => 'abc_estoppels_abc_estoppels_1',
  'source' => 'non-db',
  'module' => 'abc_Estoppels',
  'bean_name' => 'abc_Estoppels',
  'vname' => 'LBL_ABC_ESTOPPELS_ABC_ESTOPPELS_1_FROM_ABC_ESTOPPELS_L_TITLE',
  'id_name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
);
$dictionary["abc_Estoppels"]["fields"]["abc_estoppels_abc_estoppels_1"] = array (
  'name' => 'abc_estoppels_abc_estoppels_1',
  'type' => 'link',
  'relationship' => 'abc_estoppels_abc_estoppels_1',
  'source' => 'non-db',
  'module' => 'abc_Estoppels',
  'bean_name' => 'abc_Estoppels',
  'vname' => 'LBL_ABC_ESTOPPELS_ABC_ESTOPPELS_1_FROM_ABC_ESTOPPELS_R_TITLE',
  'id_name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
);
$dictionary["abc_Estoppels"]["fields"]["abc_estoppels_abc_estoppels_1_name"] = array (
  'name' => 'abc_estoppels_abc_estoppels_1_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_ABC_ESTOPPELS_ABC_ESTOPPELS_1_FROM_ABC_ESTOPPELS_R_TITLE',
  'save' => true,
  'id_name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
  'link' => 'abc_estoppels_abc_estoppels_1',
  'table' => 'abc_estoppels',
  'module' => 'abc_Estoppels',
  'rname' => 'name',
);
$dictionary["abc_Estoppels"]["fields"]["abc_estoppels_abc_estoppels_1_name"] = array (
  'name' => 'abc_estoppels_abc_estoppels_1_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_ABC_ESTOPPELS_ABC_ESTOPPELS_1_FROM_ABC_ESTOPPELS_L_TITLE',
  'save' => true,
  'id_name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
  'link' => 'abc_estoppels_abc_estoppels_1',
  'table' => 'abc_estoppels',
  'module' => 'abc_Estoppels',
  'rname' => 'name',
);
$dictionary["abc_Estoppels"]["fields"]["abc_estoppels_abc_estoppels_1abc_estoppels_ida"] = array (
  'name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_ABC_ESTOPPELS_ABC_ESTOPPELS_1_FROM_ABC_ESTOPPELS_R_TITLE_ID',
  'id_name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
  'link' => 'abc_estoppels_abc_estoppels_1',
  'table' => 'abc_estoppels',
  'module' => 'abc_Estoppels',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'left',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
$dictionary["abc_Estoppels"]["fields"]["abc_estoppels_abc_estoppels_1abc_estoppels_ida"] = array (
  'name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_ABC_ESTOPPELS_ABC_ESTOPPELS_1_FROM_ABC_ESTOPPELS_L_TITLE_ID',
  'id_name' => 'abc_estoppels_abc_estoppels_1abc_estoppels_ida',
  'link' => 'abc_estoppels_abc_estoppels_1',
  'table' => 'abc_estoppels',
  'module' => 'abc_Estoppels',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'left',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
